User.create!([
  {email: "guest@flux-capacitr.com", password: "welcome", username: "timely-guest", avatar_url: "http://www.seilchat.co.uk/download/file.php?avatar=1081_1390414737.gif", slug: "timely-guest"},
  {email: "rick@adultswim.com", password: "rickrick", username: "rickdiculous", avatar_url: "http://www.seilchat.co.uk/download/file.php?avatar=1081_1390414737.gif", slug: "rickdiculous"},
  {email: "morty@adultswim.com", password: "mortymorty", username: "mortyfied", avatar_url: "http://www.seilchat.co.uk/download/file.php?avatar=1081_1390414737.gif", slug: "mortyfied"},
  {email: "ted@stallyns.net", password: "tedted", username: "ted-like-whoa", avatar_url: "http://www.seilchat.co.uk/download/file.php?avatar=1081_1390414737.gif", slug: "loganesque"},
  {email: "bill@stallyns.net", password: "billbill", username: "bill-esque", avatar_url: "http://www.seilchat.co.uk/download/file.php?avatar=1081_1390414737.gif", slug: "bill-esque"},
  {email: "abe@whitehouse.gov", password: "lincoln", username: "vamp-slayer-abe", avatar_url: "http://www.seilchat.co.uk/download/file.php?avatar=1081_1390414737.gif", slug: "vamp-slayer-abe"},
  {email: "t2@skynet.gov", password: "arnold", username: "i-will-have-been-back", avatar_url: "http://www.seilchat.co.uk/download/file.php?avatar=1081_1390414737.gif", slug: "i-will-have-been-back"},
  {email: "calvin@watterson.com", password: "calvin", username: "spaceman-spiff", avatar_url: "http://www.seilchat.co.uk/download/file.php?avatar=1081_1390414737.gif", slug: "spaceman-spiff"},
  {email: "doc@future.com", password: "docdoc", username: "great-scott", avatar_url: "http://www.seilchat.co.uk/download/file.php?avatar=1081_1390414737.gif", slug: "great-scott"},
  {email: "marty@future.com", password: "martymarty", username: "mcfly-guy", avatar_url: "http://www.seilchat.co.uk/download/file.php?avatar=1081_1390414737.gif", slug: "mcfly-guy"},
  {email: "dalek@dalek.dalek", password: "dalekdalek", username: "x-terminate", avatar_url: "http://www.seilchat.co.uk/download/file.php?avatar=1081_1390414737.gif", slug: "x-terminate"},
  {email: "amy@tardis.com", password: "amyamy", username: "pond-hopper", avatar_url: "http://www.seilchat.co.uk/download/file.php?avatar=1081_1390414737.gif", slug: "pond-hopper"},
  {email: "rory@tardis.com", password: "roryrory", username: "rory-the-roman", avatar_url: "http://www.seilchat.co.uk/download/file.php?avatar=1081_1390414737.gif", slug: "rory-the-roman"},
  {email: "winston@downing.gov", password: "winston", username: "churchill-quote", avatar_url: "http://www.seilchat.co.uk/download/file.php?avatar=1081_1390414737.gif", slug: "churchill-quote"},
  {email: "one@gallifrey.net", password: "pertwee", username: "the-good-doctor", avatar_url: "http://www.seilchat.co.uk/download/file.php?avatar=1081_1390414737.gif", slug: "the-good-doctor"},
  {email: "nine@gallifrey.net", password: "eccleston", username: "fantastic", avatar_url: "http://www.seilchat.co.uk/download/file.php?avatar=1081_1390414737.gif", slug: "fantastic"},
  {email: "ten@gallifrey.net", password: "tennant", username: "allons-y", avatar_url: "http://www.seilchat.co.uk/download/file.php?avatar=1081_1390414737.gif", slug: "allons-y"},
  {email: "eleven@gallifrey.net", password: "mattsmith", username: "geronimo", avatar_url: "http://www.seilchat.co.uk/download/file.php?avatar=1081_1390414737.gif", slug: "geronimo"}
])
